// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAWm-TCgeD4y2_MIn-e-xSQpFXT1fmYXY',
    appId: '1:371213339875:web:dfdac79532ea50e3aec9d6',
    messagingSenderId: '371213339875',
    projectId: 'notely-65c9d',
    authDomain: 'notely-65c9d.firebaseapp.com',
    storageBucket: 'notely-65c9d.appspot.com',
    measurementId: 'G-1XP7H9PJ07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmogqqryEB9ZsCflqu1RILSzgIC1hjuck',
    appId: '1:371213339875:android:36d0e82cc74e1aeeaec9d6',
    messagingSenderId: '371213339875',
    projectId: 'notely-65c9d',
    storageBucket: 'notely-65c9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqDeBwtsWvaXBD67iNS18k-1Au1LkajMo',
    appId: '1:371213339875:ios:a361d1e6e2b67440aec9d6',
    messagingSenderId: '371213339875',
    projectId: 'notely-65c9d',
    storageBucket: 'notely-65c9d.appspot.com',
    iosClientId: '371213339875-jqj90m1c8eb1jjpbber6li5ks928u28c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqDeBwtsWvaXBD67iNS18k-1Au1LkajMo',
    appId: '1:371213339875:ios:ea7533f9ba91a90eaec9d6',
    messagingSenderId: '371213339875',
    projectId: 'notely-65c9d',
    storageBucket: 'notely-65c9d.appspot.com',
    iosClientId: '371213339875-hms6t2ouuh6a58j2ujgqci2i4fg84ua0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication.RunnerTests',
  );
}
